### ISSUE TITLE
Conflict dependencies updating to doctrine orm 2.8

### ISSUE THREAD

**Issue by DominicDetta** [Roave/psr-container-doctrine#37]
Hi, 

My goal is to upgrade `doctrine/orm` to latest version 2.8.1 but a conflict for the `doctrine/common` appeared because

this package 2.2.0 relies on `doctrine/common ^2.6`  but `doctrine/orm` applies this constraint `doctrine/common ^3.0`.

Is it possible to change the constraints on this package?

**Comment by DominicDetta** [comment]
@pauci Does that means it has been planned to do ?

**Comment by edigu** [comment]
This was also an issue when I try to upgrade my project to use migrations v3. Then a decided to create a PR to upgrade migration version here: https://github.com/Roave/psr-container-doctrine/pull/35 and relaxed dependencies to allow wider range: `^2.6 || ^3.0` But the major difference there is; I also ended up with bumping minimum PHP version to `7.4` since it's already a big BC break.

**Comment by DominicDetta** [comment]
@edigu  Thanks for your response. I'm trying to upgrade `doctrine/orm` from 2.7.5 to 2.8.1 which one would consider not a BC break but the latest version of `psr-container-doctrine` relies on `doctrine/common ^2.6` which does not match the constraints `doctrine/common ^3.0` of `doctrine/orm 2.8.1`. Do I need to create a PR (never did) to allow wider range as you mentioned? The fact is that I don't know what are the changes to accomplish this operation.

**Comment by pauci** [comment]
@DominicDetta I don't know if it's planned. I just would like to upgrade too and especially upgrade to PHP `8.0`. Maybe if I find some time, I could look on it and submit a PR, but I'm quite busy...

**Comment by internalsystemerror** [comment]
I tried a while ago to create a PR for this, but I was having issues installing the dependencies with composer v2 (using PHP 7.4) so I'll log my findings here for someone.

This required me to update `doctrine/coding-standard` to `^8.1`.
Attempting to  `composer update --prefer-lowest --prefer-stable --prefer-dist` meant that the lowest versions for `doctrine/common` `doctrine/dbal` and `doctrine/orm` were all higher than the library currently supports.
Running make showed that the tests were written for `doctrine/common` v3 due to namespace changes.

I was left with the understanding that maybe the lower version constraints aren't actually tested, so a new release may have to be BC breaking, bumping the required `doctrine/common` version to `^2.13 || ^3.0` if/when that comes out, or just `^3.0`. Using the latter bumps the required versions of `doctrine/dbal` and `doctrine/orm` also.

**Comment by DominicDetta** [comment]
I found out that the branch `master` already has relaxed dependencies: `doctrine/common": "^2.6 || ^3.0`.
Does that mean I can use master to my composer.json?

**Comment by asgrim** [comment]
> I found out that the branch `master` already has relaxed dependencies: `doctrine/common": "^2.6 || ^3.0`.
> Does that mean I can use master to my composer.json?

You are welcome to try it in your staging/development environment, don't recommend in production though!

**Comment by DominicDetta** [comment]
Ok, thanks.

**Comment by Slamdunk** [comment]
It's two and a half years [`v3`](https://github.com/Roave/psr-container-doctrine/releases/tag/3.0.0) has been released with `doctrine/common:v3` enabled, so I think we can close this.
