### ISSUE TITLE
DriverFactory.php incompatible with doctrine/common: "^3.0"

### ISSUE THREAD

**Issue by FBurner** [Roave/psr-container-doctrine#51]
Hi i noticed that /src/DriverFactory.php is not compatible with doctrine/common ^3.0
since 

use Doctrine\Common\Annotations\AnnotationReader;
use Doctrine\Common\Annotations\AnnotationRegistry;

are only available below version 3.0, so it seems the package.json is broken with psr-contrianer-doctrine 3.x

**Comment by FBurner** [comment]
It makes update to php 8.0 of this repository currently impossible since only doctrine/common 3.0 is compatible with php 8

**Comment by edigu** [comment]
You are right. If common@3.0 is decided by composer and your project has no dependency for `doctrine/annotations` in any way, this could happen. Most of the projects that I worked on where we use this library were either directly or indirectly using doctrine/annotations so far. 

In this case, I would vote for making `doctrine/annotations` an explicit dependency in composer.json since [AnnotationReader is alive there](https://github.com/doctrine/annotations/blob/1.14.x/lib/Doctrine/Common/Annotations/AnnotationReader.php)

**Comment by Ocramius** [comment]
Does this still apply after #55 ?

**Comment by Gared** [comment]
I updated to latest doctrine packages today and can confirm that my installation is broken, because AnnotationRegistry is missing now. Requiring doctrine/annotations fixed this issue for me

**Comment by Ocramius** [comment]
Can anyone here perhaps add `maglnet/composer-require-checker` to `require-dev` of this package, and make it green? That would prevent such kind of issue.
