### ISSUE TITLE
Dependency range is broken

### ISSUE THREAD

**Issue by Ocramius** [Roave/psr-container-doctrine#56]
https://github.com/Roave/psr-container-doctrine/blob/653bdbacf92ef563cd82904595b112b692067cc6/composer.json#L19

This is an exercise in "eating our own dogfood" - this is probably from the initial fork of the project, when it was first imported in `roave/`, but we should really use a stricter range here.

**Comment by asgrim** [comment]
Gah, I let this slip through in #35 sorry >.<

**Comment by Ocramius** [comment]
Happens 🤷 

Still, we should fix this.

**Comment by edigu** [comment]
Author of #35 here. Even if I do more Java than PHP nowadays, I would gladly help if you can assist me on things needs to be considered or the range we need to focus.

**Comment by Ocramius** [comment]
@edigu take it easy, it's nothing too critical.

In practice, that range needs to become:

```diff
->=7.4
+^7.4 || ~8.0.0 || ~8.1.0
```

That effectively translates to:

 * Anything between 7.4 and 8.0 (excluded)
 * anything between 8.0.0 and 8.1.0 (excluded)
 * anything between 8.1.0 and 8.2.0 (excluded)

This is because PHP is not SemVer compliant, and breaks at every minor.

**Comment by edigu** [comment]
@Ocramius here we go: https://github.com/Roave/psr-container-doctrine/pull/57

Everything looks okay in PHP 7.4, waiting CI for other builds.

Update: Omg. 8 and 8.1 already failed due to a mandatory composer update. Was there a specific reason to commit composer.lock file in this project? Isn't it needs to be re-generated as the platform version changes?
